# Generated by Django 4.1.5 on 2023-01-07 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dish_id', models.IntegerField()),
                ('dish_name', models.CharField(max_length=250)),
                ('dish_time', models.CharField(max_length=50)),
                ('dish_ingredient', models.CharField(max_length=250)),
                ('ingredient_weight', models.IntegerField()),
                ('ingredient_unit', models.CharField(max_length=10)),
            ],
        ),
    ]
